"""Build a fresh HE Standard Application Form Part B scaffold.

Produces ``templates/ria_part_b_2026.docx`` once, committed in-repo. The
file approximates the EC's Part B layout for RIA / IA: three top-level
sections (1 / 2 / 3) with the documented subsection prefixes, plus a
dedicated **AI disclosure** section bookmarked so the orchestrator
(Compliance Reviewer, S2) can fill it post-generation.

Why a real on-disk template?
- Page numbers, font, margins, and the AI-disclosure bookmark live in
  the binary so designers can swap them without code edits.
- Keeps the export path simple — render Markdown into the body, never
  build chrome.
"""

from __future__ import annotations

from io import BytesIO
from pathlib import Path

from docx import Document
from docx.document import Document as DocumentT
from docx.shared import Cm, Pt

# Section structure — docs/07 §3.2.
SECTIONS: list[tuple[str, list[tuple[str, str]]]] = [
    (
        "1. Excellence",
        [
            ("1.1", "Objectives and ambition"),
            ("1.2", "Methodology"),
            ("1.3", "State of the art"),
            ("1.4", "Open science practices"),
        ],
    ),
    (
        "2. Impact",
        [
            ("2.1", "Project's pathways towards impact"),
            ("2.2", "Measures to maximise impact"),
            ("2.3", "Summary canvas (key impact pathways)"),
        ],
    ),
    (
        "3. Implementation",
        [
            ("3.1", "Work plan and resources"),
            ("3.2", "Capacity of the participants"),
            ("3.3", "Consortium as a whole"),
        ],
    ),
]

PLACEHOLDER_TEXT = "[This subsection will be populated during proposal generation.]"
AI_DISCLOSURE_BOOKMARK = "AI_DISCLOSURE"


def build_template() -> DocumentT:
    """Return a fresh Document with the HE Part B scaffold."""

    doc = Document()

    # Page margins per EC Part B template (2.5 cm uniform).
    for section in doc.sections:
        section.top_margin = Cm(2.5)
        section.bottom_margin = Cm(2.5)
        section.left_margin = Cm(2.5)
        section.right_margin = Cm(2.5)

    styles = doc.styles
    if "Normal" in styles:
        normal = styles["Normal"]
        normal.font.name = "Calibri"
        normal.font.size = Pt(11)

    # Cover.
    title = doc.add_heading("Horizon Europe — Research and Innovation Action", level=0)
    for run in title.runs:
        run.bold = True
    subtitle = doc.add_paragraph()
    subtitle.add_run("Standard Application Form, Part B").italic = True

    title_p = doc.add_paragraph()
    title_p.add_run("Project Title: ").bold = True
    title_p.add_run("[project_title]")

    acronym_p = doc.add_paragraph()
    acronym_p.add_run("Acronym: ").bold = True
    acronym_p.add_run("[acronym]")

    # Section scaffolding.
    for section_title, subsections in SECTIONS:
        doc.add_heading(section_title, level=1)
        for code, label in subsections:
            doc.add_heading(f"{code} {label}", level=2)
            doc.add_paragraph(PLACEHOLDER_TEXT)

    # AI disclosure section — page 32 in the official EC template; we
    # insert a heading + bookmark + placeholder paragraph the
    # ComplianceReviewer (S2) will fill in via the bookmark anchor.
    doc.add_heading("Use of AI Tools in This Proposal", level=1)
    p = doc.add_paragraph()
    _add_bookmark(p, AI_DISCLOSURE_BOOKMARK)
    p.add_run(
        "[This section is auto-generated by the ComplianceReviewer agent "
        "based on per-sentence provenance metadata. Do not edit manually.]"
    ).italic = True

    # Bibliography placeholder — Hallucination Hunter populates after
    # citation verification.
    doc.add_heading("References", level=1)
    doc.add_paragraph("[Numbered references — populated post citation verification.]")

    return doc


def _add_bookmark(paragraph: object, bookmark_name: str) -> None:
    """Insert a Word bookmark at the start of ``paragraph``.

    Uses the OOXML <w:bookmarkStart>/<w:bookmarkEnd> elements directly —
    python-docx doesn't expose a typed bookmark API yet (1.2.x). The
    bookmark id namespace is keyed off the bookmark name so reruns
    don't collide on the same id.
    """

    from docx.oxml.ns import qn
    from docx.oxml.parser import OxmlElement

    # Stable id derived from the name — small, positive, no clash with
    # the few other bookmarks the template ships with.
    bookmark_id = abs(hash(bookmark_name)) % 100_000

    start = OxmlElement("w:bookmarkStart")
    start.set(qn("w:id"), str(bookmark_id))
    start.set(qn("w:name"), bookmark_name)
    end = OxmlElement("w:bookmarkEnd")
    end.set(qn("w:id"), str(bookmark_id))

    p_elem = paragraph._p  # type: ignore[attr-defined]
    p_elem.insert(0, start)
    p_elem.append(end)


def to_bytes() -> bytes:
    buf = BytesIO()
    build_template().save(buf)
    return buf.getvalue()


def main(target: Path | None = None) -> Path:
    target = target or (Path(__file__).resolve().parent / "templates" / "ria_part_b_2026.docx")
    target.parent.mkdir(parents=True, exist_ok=True)
    build_template().save(str(target))
    return target


if __name__ == "__main__":
    written = main()
    print(f"wrote: {written}")


__all__ = ["AI_DISCLOSURE_BOOKMARK", "SECTIONS", "build_template", "main", "to_bytes"]
